name: The Ludlow Lawsons
favicon: null
layout_spectrum: 0.6764056526590139
typography_spectrum: 0.7617541004437953
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6329588051885366
  lightness: 0.10462105763144791
  saturation: 0.792830441147089
  rhythmicContrast: 0.15889754379168153
purpose: []
