name: The Ludlow Lawsons
favicon: null
layout_spectrum: 0.6764056526590139
typography_spectrum: 0.7617541004437953
title: The Ludlow Lawsons
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131514'
    - '#747476'
    - '#5a533f'
    - '#d4cdaf'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.15889754379168153
purpose: []
